### ISSUE TITLE
C99

### ISSUE THREAD

**Issue by ghost** [faelys/libsoldout#10]
How about to explicitly set C standard to at least C99 ?

Because, for example [buffer.c](https://github.com/faelys/libsoldout/blob/0491217f44dcc9f3921685b5e9e07cc73f7d9a1d/buffer.c#L290) uses vsnprintf(), va_copy().
The function and macro conform to ISO/IEC 9899:1999 ("ISO C99").

see: http://en.cppreference.com/w/c/io/vfprintf
and http://en.cppreference.com/w/c/variadic/va_copy

**Comment by faelys** [comment]
I don't understand exactly what you are suggesting.

My code does follow C99 standard, chosen mostly because of the significant improvements over C89 (like `va_copy` or fixed-size integers) while the newer standard didn't exist yet.

But what do you mean by "explicitly set[ting] C standard"?

**Comment by ghost** [comment]
Sorry for not being clear.
I am just suggesting to add `-std=c99` option to CFLAGS in *makefiles.

**Comment by ghost** [comment]
...and GCC [4.X.X](https://gcc.gnu.org/onlinedocs/gcc-4.9.3/gcc/C-Dialect-Options.html#C-Dialect-Options) uses by default gnu90 + some C99 features,
but [5.X.X](https://gcc.gnu.org/onlinedocs/gcc-5.2.0/gcc/C-Dialect-Options.html#C-Dialect-Options) and [Clang](http://clang.llvm.org/docs/UsersManual.html#differences-between-various-standard-modes) use gnu11 by default.

It compiles fine with GCC 4.X.X, so it is just to be more clear with this version. )

**Comment by ghost** [comment]
merci
