### ISSUE TITLE
Makefile: purpose of the '.m' extension

### ISSUE THREAD

**Issue by ghost** [faelys/libsoldout#20]
In the [BSDmakefile](https://github.com/faelys/libsoldout/blob/74d2f518fc6969702757da0b16a2215ebbfdf683/BSDmakefile#L82-L88) and  [GNUmakefile](https://github.com/faelys/libsoldout/blob/74d2f518fc6969702757da0b16a2215ebbfdf683/GNUmakefile#L77-L80), I've found that there is support for the `.m` extension;

and gcc(1) says:

> file.m Objective-C source code

There is no Objective-C source code, so  what's the purpose of the `.m` extension ?

**Comment by faelys** [comment]
I don't think it really has a purpose. It's more likely a leftover from the template Makefile which served as a base to write this one, and which belonged to a project where C and Objective-C were mixed.

The `.m` rule can probably be safely removed.

While at it, I might also make a rule to build GNUmakefile from BSDmakefile, like in [faelys/ddns](//github.com/faelys/ddns) and probably also the reverse to keep the balance between GNU and BSD.

**Comment by ghost** [comment]
Here is a [PR](https://github.com/faelys/libsoldout/pull/29).
