### ISSUE TITLE
amalgamation version

### ISSUE THREAD

**Issue by ghost** [faelys/libsoldout#23]
What do you think about amalgamation ?
With the amalgamation it is a little bit easier to integrate and maintain into another project;
+ there could be some  performance improvements, see [the SQLite amalgamation](http://www.sqlite.org/amalgamation.html).

I have a script that creates `soldout.[ch]` from `array.[ch]`, `buffer.[ch]`, `markdown.[ch]` and `renderers.[ch]`. So, if you want, I can open a pull request..

**Comment by faelys** [comment]
To be honest, I have myself only ever used the "hand-amalgamated" version, which means basically that I just copy all `.c` and `.h` files in the project. That doesn't provide the performance benefits of having a single compilation unit, but the other benefits are there.

I don't really know whether there is really a need for that particular projects, however as a general rule, more options is better than less, as long as your script is simple and clear enough for me to maintain. So I would accept a maintainable pull request.

However I don't think I would welcome a commit of the amalgamation results (i.e. the generated files), but I would host them for stable releases besides the tarball.

**Comment by ghost** [comment]
Here is a [PR](https://github.com/faelys/libsoldout/pull/24).
