### ISSUE TITLE
Parser autolink not working

### ISSUE THREAD

**Issue by dlew** [faelys/libsoldout#3]
Given this input:

```
This should autolink: http://www.madeup.com/
```

I get this output from mkd2html:

```
<p>This should autolink: http://www.madeup.com/</p>
```

This seems to be causing other problems, for example unnecessary emphasis in URLs with underscores.

**Comment by faelys** [comment]
`libsoldout` mostly follows [John Gruber's original and official Markdown Standard](http://daringfireball.net/projects/markdown/), and what you seem to call "autolink" does not exist there. In the standard, a URL-looking piece text is just a basic piece of text.

Markdown does have the concept of [automatic links](http://daringfireball.net/projects/markdown/syntax#autolink), but these are URLs between angle brackets, like `<http://www.example.com/>`, and they are correctly transformed by `libsoldout` and `mkd2html`.

Your kind of "autolinks" would be a non-official extension to Markdown.

While the idea itself is fine, and modern markdown has all kinds of extensions, implementing it runs into of a nest of hidden difficulties: unexpected false positives, issues with telling whether punctuation is part of the URL or of the surrounding text, dealing with (recommended) scheme-relative URLs, etc.

All that on top of the fact that `libsoldout` architecture is poorly suited to recognizing URLs, so the code would necessarily be complex, inefficient and bug-ridden.

**Comment by dlew** [comment]
Thanks, that makes sense.

What do you suggest for handling links that have markdown symbols in them, for example underscores?  E.g., "http://madeup.com/this_is_my_site".  What I'm running into is that `libsoldout` parses the underscores. Perhaps I need to do a first pass of the text on my own to do the autolinking, _then_ send it to `libsoldout` for further processing?

To give more context, the issue I'm tackling here is generic user input, so I can't enforce the input to be proper official markdown.

**Comment by faelys** [comment]
In my applications, I only dealt with expert trusted users (adminstrators) that know correct Markdown syntax, and untrusted users, form whom unmarked URLs are considered spam (with a bold warning in the form, there are very few false positives).

However such a solution might not work for you, in that case I think that the best solution is a first pass on the text, adding the angle brackets if you trust the users, or added backticks (```) for code rendering if you don't (which sort of makes sense for a non-clickable link, it's a string meant to be understood by a computer). If you really don't want any special formatting in that case, you can add backslashes (`\`) before underscores in URLs detected in the first pass.

Using a first pass rather something in`libsoldout` is much easier, because `libsoldout` has a character-by-character onlline architecture, while your first pass can have knowledge of the whole text. For example, you can search for `://` and backtrack to include the URL scheme (while `libsoldout` internals cannot easily backtrack), or if you want to support scheme-relative URLs you can search for `//` and check whether there is a colon (`:`) right before, or you can filter on some specific scheme whitelist (e.g. only `http`, `https` and `ftp`). Just keep in mind the difficulties I mentioned above (especially punctuation vs URL end), it might save you a lot of unpleasantly surprised users.

**Comment by dlew** [comment]
Thanks for the advice, I think the first pass is a reasonable solution.
