### ISSUE TITLE
static analysis for the amalgamation version

### ISSUE THREAD

**Issue by ghost** [faelys/libsoldout#32]
clang-analyzer has found some bugs in the amalgamation version;
I don't know why, but in non-amalgamation version clang-analyzer cannot find them;
and it looks interesting.

For example:
Potential leak of memory pointed to by 'text' : [markdown.c:1685](https://github.com/faelys/libsoldout/blob/17850e9b345d6d827b4ddf717307fd9eaeb13859/markdown.c#L1685)

There are overall 5 bugs/warnings.
Should I post all warnings here ?

**Comment by ghost** [comment]
++ cppcheck has also found that error, but overall just 1 error.

**Comment by faelys** [comment]
That's a very good catch. If that's not too much trouble, I would welcome the full list of warnings, otherwise I will eventually install and learn to use the tool, seems very powerful.

**Comment by ghost** [comment]
How do you live without static analysis tools..? ;)

It looks like all other warnings are false positives.
Anyway here is a listing:
1. Null pointer passed as an argument to a 'nonnull' parameter : [buffer.c:192](https://github.com/faelys/libsoldout/blob/634dfd0224e9daf6434c41705ed1b98dc537caef/buffer.c#L192)
2. Called function pointer is null (null dereference) : [makrdown.c:310](https://github.com/faelys/libsoldout/blob/17850e9b345d6d827b4ddf717307fd9eaeb13859/markdown.c#L310)
3. Access to field 'size' results in a dereference of a null pointer (loaded from variable 'ret') : [markdown.c:196](https://github.com/faelys/libsoldout/blob/17850e9b345d6d827b4ddf717307fd9eaeb13859/markdown.c#L196)
4. Potential leak of memory pointed to by 'work' : [markdown.c:1199](https://github.com/faelys/libsoldout/blob/17850e9b345d6d827b4ddf717307fd9eaeb13859/markdown.c#L1199)

I recommend you to install clang-analyzer. It is able to show results in a web browser:
![analyzer_html.png](http://clang-analyzer.llvm.org/images/analyzer_html.png)

**Comment by faelys** [comment]
Honestly, these days I mostly live in Ada world, where the much stricter and stronger language semantics allow for much more powerful static analysis. Coming back from that even with clang-analyzer C feels dangerous and poorly tooled.

Back on topic, the others look indeed like false positive. unless I'm missing something:
1. Non-zero `asize` implies non-null `buffer` (where are type invariant when you need them?), and `bufgrow()` returning non-zero also implies non-null `buffer` (where are postconditions when you need them?), so `memcpy` cannot be reached with a null pointer.
2. The while loop terminates with null `action` only when `end >= size`, but then the loop body is broken before reaching the dereference. But that doesn't add up, it's a completely local analysis, so amalgamation context should change anything, and I have the (not well-informed) feeling this analysis is an easy one. There must be something else going on, but what?
3. The dynamic array is filled only with non-null values, so `ret` cannot be null. That one feels very hard to analyze automatically, an `assert` be useful here both as a safety check and as an implicit internal documentation (until we get type invariants to express that rigorously, and maybe even someday prove it).

Thanks a lot for providing the report.

**Comment by ghost** [comment]
I don't like to wait, so I fixed it: [PR#33](https://github.com/faelys/libsoldout/pull/33).

**Comment by faelys** [comment]
It looks like you caught me _again_ juggling with too many things that don't clatter noisily when they fall on the ground. I'm very sorry and I wish it won't happen again (I won't make a promise I doubt I can keep). And thanks a lot for taking it over.
