### ISSUE TITLE
static analysis

### ISSUE THREAD

**Issue by ghost** [faelys/libsoldout#8]
[cppcheck](http://cppcheck.sourceforge.net/) found:
...
[buffer.c:255](https://github.com/faelys/libsoldout/blob/84c979675cc1ac22b22b27644bf4c23b7ac58f08/buffer.c#L255) (style) Checking if unsigned variable 'len' is less than zero.
[markdown.c:267](https://github.com/faelys/libsoldout/blob/9cd8886cc9e3e9aca0517351f0f401e33f23462e/markdown.c#L267) (style) Same expression on both sides of '&&'.
...
and some other.

**Comment by ghost** [comment]
[Clang Static Analyzer](http://clang-analyzer.llvm.org/) found:

[mkd2man.c](https://github.com/faelys/libsoldout/blob/7097e8b3ead852683af87c7b7660b37684d949e7/mkd2man.c#L345) Address of stack memory associated with local variable 'datebuf' is still referred to by the global variable 'man_metadata' upon returning to the caller.  This will be a dangling reference

but I don't know how to test it...

**Comment by faelys** [comment]
Regarding `mkd2man`, it does sort of dangle, in that a pointer to `datebuf` survives the data. However, `datebuf` is on the stack of the `main` function, so it could only cause problems if anything tried to use `man_metadata` between the end of `main` and the end of program. There is usually nothing going on then, though maybe some contrived situation involving LD_PRELOAD-like might open something.

So the only value I see in addressing this is preventing the analyzer from complaining. I don't see any negative side-effect to moving `datebuf` from stack to global variable space, so why not?

**Comment by ghost** [comment]
> I don't see any negative side-effect to moving `datebuf` from stack to global variable space, so why not?

How about to drop global variable at all? i.e.:

``` patch
@@ -51,11 +51,11 @@ usage(FILE *out, const char *name) {
        "\t-t, --title\n"
        "\t\tSet the title of the manpage (default: filename)\n"); }

-static struct metadata {
+struct metadata {
    char *title;
    char *date;
    int section;
-} man_metadata;
+};

 static void
 man_text_escape(struct buf *ob, char *src, size_t size) {
@@ -236,6 +236,7 @@ main(int argc, char **argv) {
    time_t ttm;
    struct tm *tm;
    struct stat st;
+   struct metadata man_metadata;

    struct option longopts[] = {
        { "date",   no_argument,        0,  'd' },

```

**Comment by faelys** [comment]
Indeed, great analysis, thanks a lot!

I guess at this point it's obvious that I don't really master the depths of `mkd2man.c` and `mkd2latex.c`, they are contributed code that I try my best to maintain.

**Comment by faelys** [comment]
Did you have any other static analysis tool in mind, or can the issue be closed now? (or have I missed some fix?)

**Comment by ghost** [comment]
cppcheck:

one warning is remaining
**[[renderers.c:342](https://github.com/faelys/libsoldout/blob/343d59c6fd43b652dbc4e37c820ed5d8a28731d3/renderers.c#L342)]: (style) Checking if unsigned variable 'eq' is less than zero.**
...
all others not so important :)
[renderers.c:148]: (style) Clarify calculation precedence for '&' and '?'.
[renderers.c:150]: (style) Clarify calculation precedence for '&' and '?'.
[array.c:146]: (portability) Returning an integer in a function with pointer return type is not portable.

I thought, you will be running static analysis by yourself..

**Comment by faelys** [comment]
Oh sorry, I thought you reported everything from these tools, so I didn't expect to find anything more by myself.

**Comment by ghost** [comment]
:smile:

**Comment by ghost** [comment]
...and I don't have any more complaints, so I close this issue.

Thanks for fixing them :v:

**Comment by faelys** [comment]
Thanks a lot for the report :-)
